//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FashionShops
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cart
    {
        public long cart_id { get; set; }
        public long user_id { get; set; }
        public long product_id { get; set; }
        public short quantity { get; set; }
        public long size { get; set; }
        public long color { get; set; }
        public double total_price { get; set; }
    
        public virtual Color Color1 { get; set; }
        public virtual Product Product { get; set; }
        public virtual Size Size1 { get; set; }
        public virtual User User { get; set; }
    }
}
