//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FashionShops
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Order()
        {
            this.Order_Item = new HashSet<Order_Item>();
            this.Payment_Detail = new HashSet<Payment_Detail>();
        }
    
        public long order_id { get; set; }
        public long customer_id { get; set; }
        public System.DateTime order_date { get; set; }
        public double original_price { get; set; }
        public Nullable<double> reduced_price { get; set; }
        public double total_price { get; set; }
        public Nullable<long> voucher_id { get; set; }
        public string order_status { get; set; }
        public Nullable<double> transport_fee { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Order_Item> Order_Item { get; set; }
        public virtual User User { get; set; }
        public virtual Voucher Voucher { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Payment_Detail> Payment_Detail { get; set; }
    }
}
