//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FashionShops
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order_Item
    {
        public long id { get; set; }
        public long order_id { get; set; }
        public long product_id { get; set; }
        public short quantity { get; set; }
        public string size { get; set; }
        public string color { get; set; }
    
        public virtual Order Order { get; set; }
    }
}
