//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FashionShops
{
    using System;
    using System.Collections.Generic;
    
    public partial class Payment_Detail
    {
        public long id { get; set; }
        public long order_id { get; set; }
        public double amount { get; set; }
        public Nullable<long> payment_method { get; set; }
        public Nullable<int> payment_status { get; set; }
    
        public virtual Order Order { get; set; }
        public virtual Payment_Methods Payment_Methods { get; set; }
    }
}
