//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FashionShops
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class User
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public User()
        {
            this.Carts = new HashSet<Cart>();
            this.Orders = new HashSet<Order>();
            this.Product_Reviewing = new HashSet<Product_Reviewing>();
            this.Products = new HashSet<Product>();
            this.Vouchers = new HashSet<Voucher>();
        }

        public long user_id { get; set; }
        public string firstName { get; set; }
        public string lastName { get; set; }
        [MaxLength(10, ErrorMessage = "Your phone number is exceeding 10 numbers!")]
        [RegularExpression("^\\d{10}$", ErrorMessage = "Your phone number is not valid!")]
        public string phoneNumber { get; set; }
        [Required(ErrorMessage = "This field is required!")]
        [RegularExpression("^[\\w-\\.]+@([\\w-]+\\.)+[\\w-]{2,4}$", ErrorMessage = "This email is not valid!")]
        public string email { get; set; }

        [Required(ErrorMessage = "This field is required!")]
        [MaxLength(20, ErrorMessage = "username cannot exceed 20 characters!")]
        public string username { get; set; }

        [Required(ErrorMessage = "This field is required!")]
        public string password { get; set; }
        [Compare("password", ErrorMessage = "Confirm password does not match.")]
        public string confirmpassword { get; set; }
        public string newpassword { get; set; }
        public byte admin { get; set; }
        public string province { get; set; }
        public string city { get; set; }
        public string country { get; set; }
        public string address { get; set; }
        public bool rememberme { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Cart> Carts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Order> Orders { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Product_Reviewing> Product_Reviewing { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Product> Products { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Voucher> Vouchers { get; set; }
    }
}
